init 1:
    $ music_list_7dl = {}

    $ music_list_7dl["Denis Stelmakh - Afraid of Destiny"] = default_7dl_path+"Sound/music/afraid_of_destiny.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer 1"] = default_7dl_path+"Sound/music/alice_theme.ogg"
    $ music_list_7dl["Josh Powell - Anglegrinder"] = default_7dl_path+"Sound/music/anglegrinder.ogg"
    $ music_list_7dl["I am waiting for you last summer - Surrender"] = default_7dl_path+"Sound/music/are_you_there.ogg"
    $ music_list_7dl["Josh Powell - Creeping up"] = default_7dl_path+"Sound/music/areyouabully.ogg"
    $ music_list_7dl["Christina Perri - A Thousand years (Piano-Cello ThePianoGuys Cover"] = default_7dl_path+"Sound/music/ask_you_out"

    $ music_list_7dl["Touhou - Bad Apple (Receptor Cover)"] = default_7dl_path+"Sound/music/bad_apple.ogg"
    $ music_list_7dl["Josh Powell - Beat Symphonic"] = default_7dl_path+"Sound/music/beat_symphonic.ogg"
    $ music_list_7dl["Porter Robinson - Fellow Feeling (no drop edit)"] = default_7dl_path+"Sound/music/beasteye.ogg"
    $ music_list_7dl["Olafur Arnalds - Beth Theme"] = default_7dl_path+"Sound/music/beth.ogg"
    $ music_list_7dl["Clint Mansell - TOGETHER WE WILL LIVE FOREVER (guitar cover)"] = default_7dl_path+"Sound/music/breath_again.ogg"
    $ music_list_7dl["Sia - Breathe Me"] = default_7dl_path+"Sound/music/breath_me.ogg"
    $ music_list_7dl["Funczion Sounds - Heretics and Dreamers"] = default_7dl_path+"Sound/music/but_why.ogg"

    $ music_list_7dl["Kari Sigurdsson - Trailer Cat"] = default_7dl_path+"Sound/music/catch_the_hedge.ogg"
    $ music_list_7dl["James Dooley - The story of You and Me"] = default_7dl_path+"Sound/music/christmas_met.ogg"
    $ music_list_7dl["V-Flower - Close to you (guitar cover by Justin Ly)"] = default_7dl_path+"Sound/music/closetoyou.ogg"
    $ music_list_7dl["RealFaction - A forgotten past"] = default_7dl_path+"Sound/music/clueless_hope.ogg"

    $ music_list_7dl["Yurima - Kiss The rain (Acoustic Cover)"] = default_7dl_path+"Sound/music/dance_with_me.ogg"
    $ music_list_7dl["Yurima - Kiss The Rain"] = default_7dl_path+"Sound/music/dance_with_me_piano.ogg"
    $ music_list_7dl["Seether – Careless Whisper (George Michael сover)"] = default_7dl_path+"Sound/music/danceagain.ogg"
    $ music_list_7dl["Charlie Clouser - Dead Silence"] = default_7dl_path+"Sound/music/dead_silence.ogg"
    $ music_list_7dl["April Rain - Deadman on vacation"] = default_7dl_path+"Sound/music/deadman.ogg"
    $ music_list_7dl["Funczion Sounds - Deep Insude (CrossChannel OST)"] = default_7dl_path+"Sound/music/deep_inside.ogg"
    $ music_list_7dl["Emika - Drop the other(instrumental)"] = default_7dl_path+"Sound/music/dropit.ogg"
    $ music_list_7dl[u"Алексей Омельчук - Гитарный трек 11"] = default_7dl_path+"Sound/music/dv_guitar.ogg"

    $ music_list_7dl[u"Владимир Зеленцов - Emptiness"] = default_7dl_path+"Sound/music/emptiness.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer 2"] = default_7dl_path+"Sound/music/es_downmix.ogg"
    $ music_list_7dl["Josh Kramer (feat. Tina Guo) - Where The Light Goes"] = default_7dl_path+"Sound/music/escape_2.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer 3"] = default_7dl_path+"Sound/music/Everlasting_Summer_Alice.ogg"
    $ music_list_7dl["April Rain – Exodus "] = default_7dl_path+"Sound/music/Exodus.ogg"

    $ music_list_7dl["Stefano Mocini - Inside"] = default_7dl_path+"Sound/music/feel_you_inside.ogg"
    $ music_list_7dl["ATB – Trilogy (The Final Chapter)"] = default_7dl_path+"Sound/music/finale_farewell.ogg"
    $ music_list_7dl["MilkMan-DanAnother Once Ago"] = default_7dl_path+"Sound/music/forgive_or_what.ogg"
    $ music_list_7dl["Jorge Mendez - Cold"] = default_7dl_path+"Sound/music/frostwithoutyou.ogg"
    $ music_list_7dl["Tim Nyman - Full Scale Loneliness"] = default_7dl_path+"Sound/music/fsl_tn.ogg"

    $ music_list_7dl["Funczion Sounds - Slapstick"] = default_7dl_path+"Sound/music/genki.ogg"
    $ music_list_7dl["DeepCosmo - Submarine"] = default_7dl_path+"Sound/music/gonna_be_ok.ogg"
    $ music_list_7dl["Akaaka - Makkakka"] = default_7dl_path+"Sound/music/groovie.ogg"
    $ music_list_7dl["Beat Bites - Forensic Science"] = default_7dl_path+"Sound/music/guitar_under_the_window.ogg"

    $ music_list_7dl["James Dooley - Happy Endings"] = default_7dl_path+"Sound/music/happy_ending.ogg"
    $ music_list_7dl["Jack Wall - Humans Are Disappearing"] = default_7dl_path+"Sound/music/herc_death.ogg"

    $ music_list_7dl["Josh Powel - Resolution"] = default_7dl_path+"Sound/music/iamagod2.ogg"
    $ music_list_7dl["Michael Ortega - Sad Piano For a Broken Heart"] = default_7dl_path+"Sound/music/iamsadiamsorry.ogg"
    $ music_list_7dl["Ainset - Romantic score (inakrin's mix)"] = default_7dl_path+"Sound/music/iamsadiamsorry2.ogg"
    $ music_list_7dl["I am waiting for you last summer - Neon fever"] = default_7dl_path+"Sound/music/iamsadiamsorry3.ogg"
    $ music_list_7dl["Olafur arnalds – So Close (feat. Arnor Dan) 2"] = default_7dl_path+"Sound/music/intro2.ogg"
    $ music_list_7dl["Olafur arnalds – So Close (feat. Arnor Dan) 1"] = default_7dl_path+"Sound/music/intro1.ogg"
    $ music_list_7dl[u"Ганджу - I want magic"] = default_7dl_path+"Sound/music/iwantmagic.ogg"

    $ music_list_7dl["Eels - I Need Some Sleep (Piano Cover)"] = default_7dl_path+"Sound/music/kiss_you.ogg"
    $ music_list_7dl["Digital Elvis & Zero – Theme from the Ocean (OST Достучаться до небес)"] = default_7dl_path+"Sound/music/knock.ogg"

    $ music_list_7dl["ALyosha - Sweet People караоке(минус) 1"] = default_7dl_path+"Sound/music/last_pixie.ogg"
    $ music_list_7dl["Hatsune Miku feat. Kz (LiveTune) - Last Night Good Night guitar cover"] = default_7dl_path+"Sound/music/lastlight_guitar.ogg"
    $ music_list_7dl["Hatsune Miku - Last Night Good Night (piano cover by Lee Keng Tat)"] = default_7dl_path+"Sound/music/lastlight_piano.ogg"
    $ music_list_7dl["Arn Andersson - Annihilation"] = default_7dl_path+"Sound/music/laugh_throught_the_universe.ogg"
    $ music_list_7dl["Funczion Sounds - We became friends!"] = default_7dl_path+"Sound/music/lazy_olga.ogg"
    $ music_list_7dl[u"Евгений Крылатов - Лиловый Шар (metal cover)"] = default_7dl_path+"Sound/music/liliac_ball.ogg"
    $ music_list_7dl["Beat Bites - Programming Victory"] = default_7dl_path+"Sound/music/loki_on_3.ogg"
    $ music_list_7dl["James Last - Lonesome Shepherd"] = default_7dl_path+"Sound/music/lonesome_shepherd.ogg"
    $ music_list_7dl["Audiomachine - Longing"] = default_7dl_path+"Sound/music/longing.ogg"
    $ music_list_7dl["Bosa - Fun Teacher"] = default_7dl_path+"Sound/music/loop_there_you_are!.ogg"
    $ music_list_7dl["Bosa - The popular kids"] = default_7dl_path+"Sound/music/lost_without_you.ogg"
    $ music_list_7dl["Roxette - Listen To Your Heart (acousctic cover by Igor Presnyakov)"] = default_7dl_path+"Sound/music/ltyh.ogg"
    $ music_list_7dl["Rengoku Teien - Boku wa boku janai bokudeatte boku janai (2nd Edition)"] = default_7dl_path+"Sound/music/lullaby2.ogg"
    $ music_list_7dl["Л. ван Бетховен - Лунная Соната (ремикс)"] = default_7dl_path+"Sound/music/lunar_anguish.ogg"
    $ music_list_7dl["Olafur Arnalds - Lynn theme"] = default_7dl_path+"Sound/music/lynn.ogg"
    $ music_list_7dl[u"Сектор Газа - Лирика"] = default_7dl_path+"Sound/music/lyrica_sg.ogg"

    $ music_list_7dl["Bloodhound Gang - The Bad Touch"] = default_7dl_path+"Sound/music/mammal.ogg"
    $ music_list_7dl["Jack Wall - Suicide Mission"] = default_7dl_path+"Sound/music/me2ost.ogg"
    $ music_list_7dl["For The Stars - Meet Me There(Silent Owl Cover)"] = default_7dl_path+"Sound/music/meetmethere_tts.ogg"
    $ music_list_7dl["Marcus D - Kindred Spirit"] = default_7dl_path+"Sound/music/melancholy_sun.ogg"
    $ music_list_7dl[u"Алексей Омельчук - Надежда"] = default_7dl_path+"Sound/music/misery.ogg"
    $ music_list_7dl[u"Олег Анофриев - Есть Только Миг (OST «Земля Санникова»)"] = default_7dl_path+"Sound/music/moment.ogg"
    $ music_list_7dl["Tom Day - Our World"] = default_7dl_path+"Sound/music/more_than_alive.ogg"
    $ music_list_7dl["Mark Morgan - My Chrysalis Higwayman"] = default_7dl_path+"Sound/music/my_chrysalis_highwayman.ogg"
    $ music_list_7dl["Kristofferson - Where do tears go"] = default_7dl_path+"Sound/music/my_only_hope.ogg"

    $ music_list_7dl["Jassummisko - Bassment Pianist"] = default_7dl_path+"Sound/music/no_hope_left.ogg"
    $ music_list_7dl["Limp Bizkit - Nookie"] = default_7dl_path+"Sound/music/nookie.ogg"
    $ music_list_7dl["Stefano Mocini - Life"] = default_7dl_path+"Sound/music/nowyouseeme.ogg"

    $ music_list_7dl["Yiruma – River Flows in You (Cello & Piano)"] = default_7dl_path+"Sound/music/old_kiss.ogg"
    $ music_list_7dl["DeVso - When I First Met You"] = default_7dl_path+"Sound/music/ourfirstmet.ogg"
    $ music_list_7dl["Jessica Curry - Twenty One"] = default_7dl_path+"Sound/music/out_of_painkillers.ogg"
    $ music_list_7dl[u"Ясухара Таканаси - Eau de Vie (Shiki OST)"] = default_7dl_path+"Sound/music/out_of_your_tier.ogg"
    $ music_list_7dl["IA - Outer Science"] = default_7dl_path+"Sound/music/Outer_Science.ogg"

    $ music_list_7dl["Micheal Ortega - Night of rain"] = default_7dl_path+"Sound/music/pathways.ogg"
    $ music_list_7dl["Sonic Librarian - Firefly Mist"] = default_7dl_path+"Sound/music/pixies_playing.ogg"
    $ music_list_7dl["Slava Jamm feat. Please Reprise - WTCS11"] = default_7dl_path+"Sound/music/Please_Reprise.ogg"
    $ music_list_7dl["KPM Music - Bass Renaissaince 1"] = default_7dl_path+"Sound/music/polyhymnia_intro.ogg"
    $ music_list_7dl["KPM Music - Bass Renaissaince 2"] = default_7dl_path+"Sound/music/polyhymnia_main.ogg"
    $ music_list_7dl["PPK - Resurrection"] = default_7dl_path+"Sound/music/ppk.ogg"
    $ music_list_7dl["Marilyn Manson - Coma White (acoustic cover)"] = default_7dl_path+"Sound/music/prologue_1.ogg"
    $ music_list_7dl["Arn Andersson & Nights Amore - Farewell Life"] = default_7dl_path+"Sound/music/promise_to_meet_you.ogg"

    $ music_list_7dl["Sergey Eybog – Raindrops"] = default_7dl_path+"sound/sfx/raindrops_radio.ogg"
    $ music_list_7dl["Qrown - Gokagetu"] = default_7dl_path+"Sound/music/red_lights.ogg"
    $ music_list_7dl["Mitchell Broom – Redemption"] = default_7dl_path+"Sound/music/Redemption.ogg"
    $ music_list_7dl["Moonlight - Electric Cello (Inspired by Beethoven) - The Piano Guys"] = default_7dl_path+"Sound/music/refuse_to_believe.ogg"
    $ music_list_7dl["Oi Va Voi - Yesterday's Mistakes"] = default_7dl_path+"Sound/music/refuse_to_replay.ogg" 
    $ music_list_7dl["KPM Music - Change Times"] = default_7dl_path+"Sound/music/rewind.ogg"
    $ music_list_7dl["Jan Cyrka - The Right Road"] = default_7dl_path+"Sound/music/rightroad.ogg"
    $ music_list_7dl["Heavenly - The Ritual"] = default_7dl_path+"Sound/music/ritual2.ogg"
    $ music_list_7dl["The Neighbourhood - Sweater Weather (Instrumental)"] = default_7dl_path+"Sound/music/runaway.ogg"

    $ music_list_7dl["Olexandr Ignatov - Sad Piano"] = default_7dl_path+"Sound/music/Sad_Piano.ogg"
    $ music_list_7dl["19's Sound Factory - Dear (Music Box Cover)"] = default_7dl_path+"Sound/music/sam_lullaby.ogg"
    $ music_list_7dl["Scorpions - Still Loving You (Cover by Kfir Ochaion)"] = default_7dl_path+"Sound/music/scorpions.ogg"
    $ music_list_7dl["Purgatory Bunny - Light Chain"] = default_7dl_path+"Sound/music/Semische.ogg"
    $ music_list_7dl["April Rain – 7 дней лета"] = default_7dl_path+"Sound/music/seven_summer_days.ogg"
    $ music_list_7dl[u"DeepCosmo - День космонавтики"] = default_7dl_path+"Sound/music/sh_ai_rejuv.ogg"
    $ music_list_7dl["Sting - Shape of my heart (instrumental)"] = default_7dl_path+"Sound/music/shape_of_my_heart.ogg"
    $ music_list_7dl["KPM Music - She has gone"] = default_7dl_path+"Sound/music/shehasgone.ogg"
    $ music_list_7dl["Ellie Goulding - Stay Awake (guitar cover by Igor Silchenko)"] = default_7dl_path+"Sound/music/sheiscool.ogg"
    $ music_list_7dl["3L - Kōrui ni shi dzumu wa tomobito no urei (Remix)"] = default_7dl_path+"Sound/music/shib_mono.ogg"
    $ music_list_7dl["3L - Kōrui ni shi dzumu wa tomobito no urei"] = default_7dl_path+"Sound/music/shib_stereo.ogg"
    $ music_list_7dl["OST Amnesia Ukyo Melody (Rock)"] = default_7dl_path+"Sound/music/sign_of_blood.ogg"
    $ music_list_7dl["April Rain - My silent angel"] = default_7dl_path+"Sound/music/silent_angel.ogg"
    $ music_list_7dl["Buoy - ==(Time Lapse of Clouds)=="] = default_7dl_path+"Sound/music/sky_feather.ogg"
    $ music_list_7dl["Gothic Storm - We meet in dreams"] = default_7dl_path+"Sound/music/slavyas_fantazm.ogg"
    $ music_list_7dl["Beat Bites - Ghoulish Chemistry"] = default_7dl_path+"Sound/music/sneakupon.ogg"
    $ music_list_7dl["DeepCosmo - tiho (acoustic)"] = default_7dl_path+"Sound/music/so_cold.ogg"
    $ music_list_7dl["Ólafur Arnalds - Raein"] = default_7dl_path+"Sound/music/so_lonely.ogg"
    $ music_list_7dl["Adele - Someone Like You(Sungha Jung cover)"] = default_7dl_path+"Sound/music/someone_like_you_guitar.ogg"
    $ music_list_7dl[u"Сплин - Романс"] = default_7dl_path+"Sound/music/splin1.ogg"
    $ music_list_7dl["Scorpions - Still Loving You (Cover by Ozielzinho)"] = default_7dl_path+"Sound/music/stilllovingyou.ogg"
    $ music_list_7dl[u"Кино - Кончится Лето (guitar cover)"] = default_7dl_path+"Sound/music/summer_ends_soon2.ogg"

    $ music_list_7dl["Funczion Sounds - To the world of dreams"] = default_7dl_path+"Sound/music/take_my_hand.ogg"
    $ music_list_7dl[u"Акира Ямаока - Tears of pain (Silent Hill OST)"] = default_7dl_path+"Sound/music/tears_of.ogg"
    $ music_list_7dl["Hatsune Miku feat. Kz (Livetune) - Tell Your World (acoustic cover)"] = default_7dl_path+"Sound/music/tellyourworld.ogg"
    $ music_list_7dl["DeepCosmo - DVATRI"] = default_7dl_path+"Sound/music/temptation.ogg"
    $ music_list_7dl["Camelia - Splatter Party (feat. Hatsune Miku)"] = default_7dl_path+"Sound/music/tender_song.ogg"
    $ music_list_7dl["Zack Hamsey - The way"] = default_7dl_path+"Sound/music/the_way.ogg" 
    $ music_list_7dl["Hans Zimmer - Rain Man Theme"] = default_7dl_path+"Sound/music/thousand_little_things.ogg"
    $ music_list_7dl["ALyosha - Sweet People караоке(минус) 2"] = default_7dl_path+"Sound/music/thousand_of_pixies.ogg"
    $ music_list_7dl["April Rain - Exploring yourself with a knife"] = default_7dl_path+"Sound/music/tilltheend.ogg"
    $ music_list_7dl["Tim McMorris - Translation (Inspirational One)"] = default_7dl_path+"Sound/music/timetowakeup.ogg"
    $ music_list_7dl[u"Владимир Розанов - С запада на восток"] = default_7dl_path+"Sound/music/to_the_sunrise.ogg"
    $ music_list_7dl["Broove - |oove|Heartbeats"] = default_7dl_path+"Sound/music/too_quiet.ogg"

    $ music_list_7dl["Vflower - Close to you (feat. Justin Ly)"] = default_7dl_path+"Sound/music/uncertainity.ogg"
    $ music_list_7dl["April Rain - Violent Passion Surrogate"] = default_7dl_path+"Sound/music/uneven_me.ogg" 
    $ music_list_7dl["Audiomachine - Unfinished Life"] = default_7dl_path+"Sound/music/unfinished_life.ogg"
    $ music_list_7dl["Martin O'Donnel - Unforgotten"] = default_7dl_path+"Sound/music/Unforgotten.ogg"
    $ music_list_7dl["April Rain – Мы будем жить"] = default_7dl_path+"Sound/music/unfulfilled.ogg"
    $ music_list_7dl["The Ring OST - Samara's Song(Piano Cover)"] = default_7dl_path+"Sound/music/unholy_you.ogg"

    $ music_list_7dl["Mattashi - Together"] = default_7dl_path+"Sound/music/vale.ogg"
    $ music_list_7dl["Marilyn Manson - If I could be your vampire"] = default_7dl_path+"Sound/music/vampire.ogg"

    $ music_list_7dl["Limp Bizkit - Walking Away"] = default_7dl_path+"Sound/music/walkingaway.ogg"
    $ music_list_7dl["Kaivaan ft. Hikaru Station - Escape (Acoustic guitar cover)"] = default_7dl_path+"Sound/music/what_am_i_doing_here.ogg"
    $ music_list_7dl["DeVso - DeVso-Music-The Avengers"] = default_7dl_path+"Sound/music/what_cost.ogg"
    $ music_list_7dl["Curse - Und was ist jetzt (Instrumental)"] = default_7dl_path+"Sound/music/whatnow.ogg"
    $ music_list_7dl["Funczion Sounds - Taking hand in hand"] = default_7dl_path+"Sound/music/wheres_wonderland.ogg"
    $ music_list_7dl["Olafur Arnalds - Near Light"] = default_7dl_path+"Sound/music/will_you.ogg"
    $ music_list_7dl[u"Евгений Крылатов - Гостья из будущего OST"] = default_7dl_path+"Sound/music/wonderful_faraway.ogg"

    $ music_list_7dl["Kabaneri of the Iron Fortress (Fingerstyle Guitar Cover)"] = default_7dl_path+"Sound/music/you_are_human.ogg"
    $ music_list_7dl["Kabaneri of the Iron Fortress (Piano Cover)"] = default_7dl_path+"Sound/music/you_are_soul.ogg"
    $ music_list_7dl["Ninelie Kabaneri of the Iron Fortress Ending Orchestral Cover Mike Reed IX"] = default_7dl_path+"Sound/music/you_are_star.ogg"
    $ music_list_7dl["Michael John Gordon - The end (Wolfenstein The Old Blood OST)"] = default_7dl_path+"Sound/music/you_were_late.ogg"
    $ music_list_7dl["Kári Sigurðsson - Stay"] = default_7dl_path+"Sound/music/youareours.ogg"
    $ music_list_7dl["Tom Day - Going Home"] = default_7dl_path+"Sound/music/your_life.ogg"
    $ music_list_7dl["Ólafur Arnalds - This Place Was A Shelter"] = default_7dl_path+"Sound/music/youre_not_real.ogg"
