init 1:
    $ music_list_7dl = {}

    $ music_list_7dl["Denis Stelmakh - Afraid of Destiny"] = default_7dl_path+"Sound/music/afraid_of_destiny_7dl.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer (cut 1)"] = default_7dl_path+"Sound/music/alice_theme_7dl.ogg"
    $ music_list_7dl["Josh Powell - Anglegrinder"] = default_7dl_path+"Sound/music/anglegrinder_7dl.ogg"
    $ music_list_7dl["I am waiting for you last summer - Surrender"] = default_7dl_path+"Sound/music/are_you_there_7dl.ogg"
    $ music_list_7dl["Josh Powell - Creeping up"] = default_7dl_path+"Sound/music/areyouabully_7dl.ogg"
    $ music_list_7dl["Christina Perri - A Thousand years (Piano-Cello ThePianoGuys Cover)"] = default_7dl_path+"Sound/music/ask_you_out_7dl.ogg"

    $ music_list_7dl["Touhou - Bad Apple (Receptor Cover)"] = default_7dl_path+"Sound/music/bad_apple_7dl.ogg"
    $ music_list_7dl["Josh Powell - Beat Symphonic"] = default_7dl_path+"Sound/music/beat_symphonic_7dl.ogg"
    $ music_list_7dl["Porter Robinson - Fellow Feeling (no drop edit)"] = default_7dl_path+"Sound/music/beasteye_7dl.ogg"
    $ music_list_7dl["Olafur Arnalds - Beth Theme"] = default_7dl_path+"Sound/music/beth_7dl.ogg"
    $ music_list_7dl["Clint Mansell - TOGETHER WE WILL LIVE FOREVER (guitar cover)"] = default_7dl_path+"Sound/music/breath_again_7dl.ogg"
    $ music_list_7dl["Sia - Breathe Me"] = default_7dl_path+"Sound/music/breath_me_7dl.ogg"
    $ music_list_7dl["Funczion Sounds - Heretics and Dreamers"] = default_7dl_path+"Sound/music/but_why_7dl.ogg"

    $ music_list_7dl["Kari Sigurdsson - Trailer Cat"] = default_7dl_path+"Sound/music/catch_the_hedge_7dl.ogg"
    $ music_list_7dl["James Dooley - The story of You and Me"] = default_7dl_path+"Sound/music/christmas_met_7dl.ogg"
    $ music_list_7dl["V-Flower - Close to you (guitar cover by Justin Ly)"] = default_7dl_path+"Sound/music/closetoyou_7dl.ogg"
    $ music_list_7dl["RealFaction - A forgotten past"] = default_7dl_path+"Sound/music/clueless_hope_7dl.ogg"

    $ music_list_7dl["Yurima - Kiss The rain (Acoustic Cover)"] = default_7dl_path+"Sound/music/dance_with_me_7dl.ogg"
    $ music_list_7dl["Yurima - Kiss The Rain"] = default_7dl_path+"Sound/music/dance_with_me_piano_7dl.ogg"
    $ music_list_7dl["Seether – Careless Whisper (George Michael сover)"] = default_7dl_path+"Sound/music/danceagain_7dl.ogg"
    $ music_list_7dl["Charlie Clouser - Dead Silence"] = default_7dl_path+"Sound/music/dead_silence_7dl.ogg"
    $ music_list_7dl["April Rain - Deadman on vacation"] = default_7dl_path+"Sound/music/deadman_7dl.ogg"
    $ music_list_7dl["Funczion Sounds - Deep Insude (CrossChannel OST)"] = default_7dl_path+"Sound/music/deep_inside_7dl.ogg"
    $ music_list_7dl["Emika - Drop the other(instrumental)"] = default_7dl_path+"Sound/music/dropit_7dl.ogg"
    $ music_list_7dl[u"Алексей Омельчук - Гитарный трек 11"] = default_7dl_path+"Sound/music/dv_guitar_7dl.ogg"

    $ music_list_7dl[u"Владимир Зеленцов - Emptiness"] = default_7dl_path+"Sound/music/emptiness_7dl.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer (cut 2)"] = default_7dl_path+"Sound/music/es_downmix_7dl.ogg"
    $ music_list_7dl["Josh Kramer (feat. Tina Guo) - Where The Light Goes"] = default_7dl_path+"Sound/music/escape_2_7dl.ogg"
    $ music_list_7dl[u"С. Ейбог feat. Liru - Everlasting Summer"] = default_7dl_path+"Sound/music/Everlasting_Summer_Alice_7dl.ogg"
    $ music_list_7dl["April Rain – Exodus "] = default_7dl_path+"Sound/music/Exodus_7dl.ogg"

    $ music_list_7dl["Stefano Mocini - Inside"] = default_7dl_path+"Sound/music/feel_you_inside_7dl.ogg"
    $ music_list_7dl["ATB – Trilogy (The Final Chapter)"] = default_7dl_path+"Sound/music/finale_farewell_7dl.ogg"
    $ music_list_7dl["MilkMan-DanAnother Once Ago"] = default_7dl_path+"Sound/music/forgive_or_what_7dl.ogg"
    $ music_list_7dl["Jorge Mendez - Cold"] = default_7dl_path+"Sound/music/frostwithoutyou_7dl.ogg"
    $ music_list_7dl["Tim Nyman - Full Scale Loneliness"] = default_7dl_path+"Sound/music/fsl_tn_7dl.ogg"

    $ music_list_7dl["Funczion Sounds - Slapstick"] = default_7dl_path+"Sound/music/genki_7dl.ogg"
    $ music_list_7dl["DeepCosmo - Submarine"] = default_7dl_path+"Sound/music/gonna_be_ok_7dl.ogg"
    $ music_list_7dl["Akaaka - Makkakka"] = default_7dl_path+"Sound/music/groovie_7dl.ogg"
    $ music_list_7dl["Beat Bites - Forensic Science"] = default_7dl_path+"Sound/music/guitar_under_the_window_7dl.ogg"

    $ music_list_7dl["James Dooley - Happy Endings"] = default_7dl_path+"Sound/music/happy_ending_7dl.ogg"
    $ music_list_7dl["Jack Wall - Humans Are Disappearing"] = default_7dl_path+"Sound/music/herc_death_7dl.ogg"

    $ music_list_7dl["Josh Powel - Resolution"] = default_7dl_path+"Sound/music/iamagod2_7dl.ogg"
    $ music_list_7dl["Michael Ortega - Sad Piano For a Broken Heart"] = default_7dl_path+"Sound/music/iamsadiamsorry_7dl.ogg"
    $ music_list_7dl["Ainset - Romantic score (inakrin's mix)"] = default_7dl_path+"Sound/music/iamsadiamsorry2_7dl.ogg"
    $ music_list_7dl["I am waiting for you last summer - Neon fever"] = default_7dl_path+"Sound/music/iamsadiamsorry3_7dl.ogg"
    $ music_list_7dl["Olafur arnalds – So Close (feat. Arnor Dan) 2"] = default_7dl_path+"Sound/music/intro2_7dl.ogg"
    $ music_list_7dl["Olafur arnalds – So Close (feat. Arnor Dan) 1"] = default_7dl_path+"Sound/music/intro1_7dl.ogg"
    $ music_list_7dl[u"Ганджу - I want magic"] = default_7dl_path+"Sound/music/iwantmagic_7dl.ogg"

    $ music_list_7dl["Eels - I Need Some Sleep (Piano Cover)"] = default_7dl_path+"Sound/music/kiss_you_7dl.ogg"
    $ music_list_7dl["Digital Elvis & Zero – Theme from the Ocean (OST Достучаться до небес)"] = default_7dl_path+"Sound/music/knock_7dl.ogg"

    $ music_list_7dl["ALyosha - Sweet People караоке (минус) (cut)"] = default_7dl_path+"Sound/music/last_pixie_7dl.ogg"
    $ music_list_7dl["Hatsune Miku feat. Kz (LiveTune) - Last Night Good Night guitar cover"] = default_7dl_path+"Sound/music/lastlight_guitar_7dl.ogg"
    $ music_list_7dl["Hatsune Miku - Last Night Good Night (piano cover by Lee Keng Tat)"] = default_7dl_path+"Sound/music/lastlight_piano_7dl.ogg"
    $ music_list_7dl["Arn Andersson - Annihilation"] = default_7dl_path+"Sound/music/laugh_throught_the_universe_7dl.ogg"
    $ music_list_7dl["Funczion Sounds - We became friends!"] = default_7dl_path+"Sound/music/lazy_olga_7dl.ogg"
    $ music_list_7dl[u"Евгений Крылатов - Лиловый Шар (metal cover)"] = default_7dl_path+"Sound/music/liliac_ball_7dl.ogg"
    $ music_list_7dl["Beat Bites - Programming Victory"] = default_7dl_path+"Sound/music/loki_on_3_7dl.ogg"
    $ music_list_7dl["James Last - Lonesome Shepherd"] = default_7dl_path+"Sound/music/lonesome_shepherd_7dl.ogg"
    $ music_list_7dl["Audiomachine - Longing"] = default_7dl_path+"Sound/music/longing_7dl.ogg"
    $ music_list_7dl["Bosa - Fun Teacher"] = default_7dl_path+"Sound/music/loop_there_you_are!_7dl.ogg"
    $ music_list_7dl["Bosa - The popular kids"] = default_7dl_path+"Sound/music/lost_without_you_7dl.ogg"
    $ music_list_7dl["Roxette - Listen To Your Heart (acousctic cover by Igor Presnyakov)"] = default_7dl_path+"Sound/music/ltyh_7dl.ogg"
    $ music_list_7dl["Rengoku Teien - Boku wa boku janai bokudeatte boku janai (2nd Edition)"] = default_7dl_path+"Sound/music/lullaby2_7dl.ogg"
    $ music_list_7dl["Л. ван Бетховен - Лунная Соната (ремикс)"] = default_7dl_path+"Sound/music/lunar_anguish_7dl.ogg"
    $ music_list_7dl["Olafur Arnalds - Lynn theme"] = default_7dl_path+"Sound/music/lynn_7dl.ogg"
    $ music_list_7dl[u"Сектор Газа - Лирика"] = default_7dl_path+"Sound/music/lyrica_sg_7dl.ogg"

    $ music_list_7dl["Bloodhound Gang - The Bad Touch"] = default_7dl_path+"Sound/music/mammal_7dl.ogg"
    $ music_list_7dl["Jack Wall - Suicide Mission"] = default_7dl_path+"Sound/music/me2ost_7dl.ogg"
    $ music_list_7dl["For The Stars - Meet Me There(Silent Owl Cover)"] = default_7dl_path+"Sound/music/meetmethere_tts_7dl.ogg"
    $ music_list_7dl["Marcus D - Kindred Spirit"] = default_7dl_path+"Sound/music/melancholy_sun_7dl.ogg"
    $ music_list_7dl[u"Алексей Омельчук - Надежда"] = default_7dl_path+"Sound/music/misery_2_7dl.ogg"
    $ music_list_7dl[u"Олег Анофриев - Есть Только Миг (OST «Земля Санникова»)"] = default_7dl_path+"Sound/music/moment_7dl.ogg"
    $ music_list_7dl["Tom Day - Our World"] = default_7dl_path+"Sound/music/more_than_alive_7dl.ogg"
    $ music_list_7dl["Mark Morgan - My Chrysalis Higwayman"] = default_7dl_path+"Sound/music/my_chrysalis_highwayman_7dl.ogg"
    $ music_list_7dl["Kristofferson - Where do tears go"] = default_7dl_path+"Sound/music/my_only_hope_7dl.ogg"

    $ music_list_7dl["Jassummisko - Bassment Pianist"] = default_7dl_path+"Sound/music/no_hope_left_7dl.ogg"
    $ music_list_7dl["Limp Bizkit - Nookie"] = default_7dl_path+"Sound/music/nookie_7dl.ogg"
    $ music_list_7dl["Stefano Mocini - Life"] = default_7dl_path+"Sound/music/nowyouseeme_7dl.ogg"

    $ music_list_7dl["Yiruma – River Flows in You (Cello & Piano)"] = default_7dl_path+"Sound/music/old_kiss_7dl.ogg"
    $ music_list_7dl["DeVso - When I First Met You"] = default_7dl_path+"Sound/music/ourfirstmet_7dl.ogg"
    $ music_list_7dl["Jessica Curry - Twenty One"] = default_7dl_path+"Sound/music/out_of_painkillers_7dl.ogg"
    $ music_list_7dl[u"Ясухара Таканаси - Eau de Vie (Shiki OST)"] = default_7dl_path+"Sound/music/out_of_your_tier_7dl.ogg"
    $ music_list_7dl["IA - Outer Science"] = default_7dl_path+"Sound/music/Outer_Science_7dl.ogg"

    $ music_list_7dl["Micheal Ortega - Night of rain"] = default_7dl_path+"Sound/music/pathways_7dl.ogg"
    $ music_list_7dl["Sonic Librarian - Firefly Mist"] = default_7dl_path+"Sound/music/pixies_playing_7dl.ogg"
    $ music_list_7dl["Slava Jamm feat. Please Reprise - WTCS11"] = default_7dl_path+"Sound/music/Please_Reprise_7dl.ogg"
    $ music_list_7dl["KPM Music - Bass Renaissaince 1"] = default_7dl_path+"Sound/music/polyhymnia_intro_7dl.ogg"
    $ music_list_7dl["KPM Music - Bass Renaissaince 2"] = default_7dl_path+"Sound/music/polyhymnia_main_7dl.ogg"
    $ music_list_7dl["PPK - Resurrection"] = default_7dl_path+"Sound/music/ppk_7dl.ogg"
    $ music_list_7dl["Marilyn Manson - Coma White (acoustic cover)"] = default_7dl_path+"Sound/music/prologue_2_7dl.ogg"
    $ music_list_7dl["Arn Andersson & Nights Amore - Farewell Life"] = default_7dl_path+"Sound/music/promise_to_meet_you_7dl.ogg"

    $ music_list_7dl["Sergey Eybog – Raindrops"] = default_7dl_path+"sound/sfx/raindrops_radio_7dl.ogg"
    $ music_list_7dl["Qrown - Gokagetu"] = default_7dl_path+"Sound/music/red_lights_7dl.ogg"
    $ music_list_7dl["Mitchell Broom – Redemption"] = default_7dl_path+"Sound/music/Redemption_7dl.ogg"
    $ music_list_7dl["Moonlight - Electric Cello (Inspired by Beethoven) - The Piano Guys"] = default_7dl_path+"Sound/music/refuse_to_believe_7dl.ogg"
    $ music_list_7dl["Oi Va Voi - Yesterday's Mistakes"] = default_7dl_path+"Sound/music/refuse_to_replay_7dl.ogg" 
    $ music_list_7dl["KPM Music - Change Times"] = default_7dl_path+"Sound/music/rewind_7dl.ogg"
    $ music_list_7dl["Jan Cyrka - The Right Road"] = default_7dl_path+"Sound/music/rightroad_7dl.ogg"
    $ music_list_7dl["Heavenly - The Ritual"] = default_7dl_path+"Sound/music/ritual2_7dl.ogg"
    $ music_list_7dl["The Neighbourhood - Sweater Weather (Instrumental)"] = default_7dl_path+"Sound/music/runaway_7dl.ogg"

    $ music_list_7dl["Olexandr Ignatov - Sad Piano"] = default_7dl_path+"Sound/music/Sad_Piano_7dl.ogg"
    $ music_list_7dl["19's Sound Factory - Dear (Music Box Cover)"] = default_7dl_path+"Sound/music/sam_lullaby_7dl.ogg"
    $ music_list_7dl["Scorpions - Still Loving You (Cover by Kfir Ochaion)"] = default_7dl_path+"Sound/music/scorpions_7dl.ogg"
    $ music_list_7dl["Purgatory Bunny - Light Chain"] = default_7dl_path+"Sound/music/Semische_7dl.ogg"
    $ music_list_7dl["April Rain – 7 дней лета"] = default_7dl_path+"Sound/music/seven_summer_days_7dl.ogg"
    $ music_list_7dl[u"DeepCosmo - День космонавтики"] = default_7dl_path+"Sound/music/sh_ai_rejuv_7dl.ogg"
    $ music_list_7dl["Sting - Shape of my heart (instrumental)"] = default_7dl_path+"Sound/music/shape_of_my_heart_7dl.ogg"
    $ music_list_7dl["KPM Music - She has gone"] = default_7dl_path+"Sound/music/shehasgone_7dl.ogg"
    $ music_list_7dl["Ellie Goulding - Stay Awake (guitar cover by Igor Silchenko)"] = default_7dl_path+"Sound/music/sheiscool_7dl.ogg"
    $ music_list_7dl["3L - Kōrui ni shi dzumu wa tomobito no urei (Remix)"] = default_7dl_path+"Sound/music/shib_mono_7dl.ogg"
    $ music_list_7dl["3L - Kōrui ni shi dzumu wa tomobito no urei"] = default_7dl_path+"Sound/music/shib_stereo_7dl.ogg"
    $ music_list_7dl["OST Amnesia Ukyo Melody (Rock)"] = default_7dl_path+"Sound/music/sign_of_blood_7dl.ogg"
    $ music_list_7dl["April Rain - My silent angel"] = default_7dl_path+"Sound/music/silent_angel_7dl.ogg"
    $ music_list_7dl["Buoy - ==(Time Lapse of Clouds)=="] = default_7dl_path+"Sound/music/sky_feather_7dl.ogg"
    $ music_list_7dl["Gothic Storm - We meet in dreams"] = default_7dl_path+"Sound/music/slavyas_fantazm_7dl.ogg"
    $ music_list_7dl["Beat Bites - Ghoulish Chemistry"] = default_7dl_path+"Sound/music/sneakupon_7dl.ogg"
    $ music_list_7dl["DeepCosmo - tiho (acoustic)"] = default_7dl_path+"Sound/music/so_cold_7dl.ogg"
    $ music_list_7dl["Ólafur Arnalds - Raein"] = default_7dl_path+"Sound/music/so_lonely_7dl.ogg"
    $ music_list_7dl["Adele - Someone Like You(Sungha Jung cover)"] = default_7dl_path+"Sound/music/someone_like_you_guitar_7dl.ogg"
    $ music_list_7dl[u"Сплин - Романс"] = default_7dl_path+"Sound/music/splin1_7dl.ogg"
    $ music_list_7dl["Scorpions - Still Loving You (Cover by Ozielzinho)"] = default_7dl_path+"Sound/music/stilllovingyou_7dl.ogg"
    $ music_list_7dl[u"Кино - Кончится Лето (guitar cover)"] = default_7dl_path+"Sound/music/summer_ends_soon2_7dl.ogg"

    $ music_list_7dl["Funczion Sounds - To the world of dreams"] = default_7dl_path+"Sound/music/take_my_hand_7dl.ogg"
    $ music_list_7dl[u"Акира Ямаока - Tears of pain (Silent Hill OST)"] = default_7dl_path+"Sound/music/tears_of_7dl.ogg"
    $ music_list_7dl["Hatsune Miku feat. Kz (Livetune) - Tell Your World (acoustic cover)"] = default_7dl_path+"Sound/music/tellyourworld_7dl.ogg"
    $ music_list_7dl["DeepCosmo - DVATRI"] = default_7dl_path+"Sound/music/temptation_7dl.ogg"
    $ music_list_7dl["Camelia - Splatter Party (feat. Hatsune Miku)"] = default_7dl_path+"Sound/music/tender_song_7dl.ogg"
    $ music_list_7dl["Zack Hamsey - The way"] = default_7dl_path+"Sound/music/the_way_7dl.ogg" 
    $ music_list_7dl["Hans Zimmer - Rain Man Theme"] = default_7dl_path+"Sound/music/thousand_little_things_7dl.ogg"
    $ music_list_7dl["ALyosha - Sweet People караоке (минус)"] = default_7dl_path+"Sound/music/thousand_of_pixies_7dl.ogg"
    $ music_list_7dl["April Rain - Exploring yourself with a knife"] = default_7dl_path+"Sound/music/tilltheend_7dl.ogg"
    $ music_list_7dl["Tim McMorris - Translation (Inspirational One)"] = default_7dl_path+"Sound/music/timetowakeup_7dl.ogg"
    $ music_list_7dl[u"Владимир Розанов - С запада на восток"] = default_7dl_path+"Sound/music/to_the_sunrise_7dl.ogg"
    $ music_list_7dl["Broove - |oove|Heartbeats"] = default_7dl_path+"Sound/music/too_quiet_7dl.ogg"

    $ music_list_7dl["Vflower - Close to you (feat. Justin Ly)"] = default_7dl_path+"Sound/music/uncertainity_7dl.ogg"
    $ music_list_7dl["April Rain - Violent Passion Surrogate"] = default_7dl_path+"Sound/music/uneven_me_7dl.ogg" 
    $ music_list_7dl["Audiomachine - Unfinished Life"] = default_7dl_path+"Sound/music/unfinished_life_7dl.ogg"
    $ music_list_7dl["Martin O'Donnel - Unforgotten"] = default_7dl_path+"Sound/music/Unforgotten_7dl.ogg"
    $ music_list_7dl["April Rain – Мы будем жить"] = default_7dl_path+"Sound/music/unfulfilled_7dl.ogg"
    $ music_list_7dl["The Ring OST - Samara's Song(Piano Cover)"] = default_7dl_path+"Sound/music/unholy_you_7dl.ogg"

    $ music_list_7dl["Mattashi - Together"] = default_7dl_path+"Sound/music/vale_7dl.ogg"
    $ music_list_7dl["Marilyn Manson - If I could be your vampire"] = default_7dl_path+"Sound/music/vampire_7dl.ogg"

    $ music_list_7dl["DeadPunk - Regret"] = default_7dl_path+"Sound/music/walkingaway_7dl.ogg"
    $ music_list_7dl["Kaivaan ft. Hikaru Station - Escape (Acoustic guitar cover)"] = default_7dl_path+"Sound/music/what_am_i_doing_here_7dl.ogg"
    $ music_list_7dl["DeVso - DeVso-Music-The Avengers"] = default_7dl_path+"Sound/music/what_cost_7dl.ogg"
    $ music_list_7dl["Curse - Und was ist jetzt (Instrumental)"] = default_7dl_path+"Sound/music/whatnow_7dl.ogg"
    $ music_list_7dl["Funczion Sounds - Taking hand in hand"] = default_7dl_path+"Sound/music/wheres_wonderland_7dl.ogg"
    $ music_list_7dl["Olafur Arnalds - Near Light"] = default_7dl_path+"Sound/music/will_you_7dl.ogg"
    $ music_list_7dl[u"Евгений Крылатов - Гостья из будущего OST"] = default_7dl_path+"Sound/music/wonderful_faraway_7dl.ogg"

    $ music_list_7dl["Kabaneri of the Iron Fortress (Fingerstyle Guitar Cover)"] = default_7dl_path+"Sound/music/you_are_human_7dl.ogg"
    $ music_list_7dl["Kabaneri of the Iron Fortress (Piano Cover)"] = default_7dl_path+"Sound/music/you_are_soul_7dl.ogg"
    $ music_list_7dl["Ninelie Kabaneri of the Iron Fortress Ending Orchestral Cover Mike Reed IX"] = default_7dl_path+"Sound/music/you_are_star_7dl.ogg"
    $ music_list_7dl["Michael John Gordon - The end (Wolfenstein The Old Blood OST)"] = default_7dl_path+"Sound/music/you_were_late_7dl.ogg"
    $ music_list_7dl["Kári Sigurðsson - Stay"] = default_7dl_path+"Sound/music/youareours_7dl.ogg"
    $ music_list_7dl["Tom Day - Going Home"] = default_7dl_path+"Sound/music/your_life_7dl.ogg"
    $ music_list_7dl["Ólafur Arnalds - This Place Was A Shelter"] = default_7dl_path+"Sound/music/youre_not_real_7dl.ogg"

#0.34.а
    $ music_list_7dl["Olafur Arnalds - Brim"] = default_7dl_path+"Sound/music/brim_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Quirky Dog"] = default_7dl_path+"Sound/music/bureaucracy_7dl.ogg"
    $ music_list_7dl["Pachebel - Canon D (flamenco ver)"] = default_7dl_path+"Sound/music/canon_d_flamenco_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Carefree"] = default_7dl_path+"Sound/music/carefree_7dl.ogg"
    $ music_list_7dl["Matt Quentin - Waves"] = default_7dl_path+"Sound/music/everyday_7dl.ogg"
    $ music_list_7dl["Olafur Arnalds - Fyrsta"] = default_7dl_path+"Sound/music/fyrsta_7dl.ogg"
    $ music_list_7dl["Hungarian Dances No 5 J Brahms - Passepartout Piano Duo"] = default_7dl_path+"Sound/music/hdance_5_7dl.ogg"
    $ music_list_7dl["Potsu x Lando! - Breakfast"] = default_7dl_path+"Sound/music/hug_me_already_7dl.ogg"
    $ music_list_7dl["Joakim Karud - Dreams"] = default_7dl_path+"Sound/music/imfine_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Gymnopedie No 1"] = default_7dl_path+"Sound/music/midday_reverie_7dl.ogg"
    $ music_list_7dl["Ólafur Arnalds - 1440"] = default_7dl_path+"Sound/music/nap_one_7dl.ogg"
    $ music_list_7dl["Just Big Hills - Shinjuku"] = default_7dl_path+"Sound/music/one_little_lone_cloud_7dl.ogg"
    $ music_list_7dl["DEADPunk - 7dl intro"] = default_7dl_path+"Sound/music/sammy_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Your Call High Quality"] = default_7dl_path+"Sound/music/shappihn_7dl.ogg"
    $ music_list_7dl["Orca Vibes - Gypsy"] = default_7dl_path+"Sound/music/shestheone_7dl.ogg"
    $ music_list_7dl["DEADPunk - 7dl melody2"] = default_7dl_path+"Sound/music/snatch_7dl.ogg"
    $ music_list_7dl["Slot - Круги на воде (instrumental)"] = default_7dl_path+"Sound/music/so_be_it_7dl.ogg"
    $ music_list_7dl["SURF - Take Care"] = default_7dl_path+"Sound/music/surf_7dl.ogg"
    $ music_list_7dl["Mattdeguia - Daylight"] = default_7dl_path+"Sound/music/too_serious_7dl.ogg"
#0.34.b
    $ music_list_7dl["DeadPunk - Despair"] = default_7dl_path+"Sound/music/despair_7dl.ogg"
    $ music_list_7dl["Steezy Prime - Explore"] = default_7dl_path+"Sound/music/explore_7dl.ogg"
    $ music_list_7dl["ППВК - Последнее лето"] = default_7dl_path+"Sound/music/last_summer_7dl.ogg"
    $ music_list_7dl["ППВК - Волшебство уходит"] = default_7dl_path+"Sound/music/magic_is_gone_7dl.ogg"
    $ music_list_7dl["Matt Quentin - Morning Dew"] = default_7dl_path+"Sound/music/Morning_Dew_7dl.ogg"
    $ music_list_7dl["DeadPunk - PleaseStopIt"] = default_7dl_path+"Sound/music/PleaseStopItMastered_7dl.ogg"
    $ music_list_7dl["Kazam - Raindrops"] = default_7dl_path+"Sound/music/raindrops_7dl.ogg"
    $ music_list_7dl["DeadPunk - Vibe"] = default_7dl_path+"Sound/music/Vibe_7dl.ogg"
#0.35.a
    $ music_list_7dl["Clint Mansell - TOGETHER WE WILL LIVE FOREVER (guitar cover)"] = default_7dl_path+"Sound/music/breath_again_slow_7dl.ogg"
    $ music_list_7dl["Beat Bites - Game of Shadows"] = default_7dl_path+"Sound/music/game_of_shadows_7dl.ogg"
    $ music_list_7dl["Beat Bites - Last Train Home"] = default_7dl_path+"Sound/music/lth_7d.ogg"
    $ music_list_7dl["Olafur Arnalds - Not Alone"] = default_7dl_path+"Sound/music/not_alone_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Your Call High Quality"] = default_7dl_path+"Sound/music/shappihn_7dl.ogg"
    $ music_list_7dl["April Rain - Im All Crying Inside"] = default_7dl_path+"Sound/music/tearing_sobs_7dl.ogg"
    $ music_list_7dl["UNKNOWN"] = default_7dl_path+"Sound/music/yume_akari_7dl.ogg"
    $ music_list_7dl["Kevin MacLeod - Niles Blues"] = default_7dl_path+"Sound/music/viola_7dl.ogg"
    $ music_list_7dl["Аревик Аветисян – Воспоминание"] = default_7dl_path+"Sound/music/sorrow_7dl.ogg"
    $ music_list_7dl["DeadPunk - Smells Like My Grave"] = default_7dl_path+"Sound/music/smlg_7dl.ogg"
#0.36.a
    $ music_list_7dl["Julian Kruse - Fallen From The Sky"] = default_7dl_path+"Sound/music/think_again_7dl.ogg"
    $ music_list_7dl["AOA - Miniskirt"] = default_7dl_path+"Sound/music/you_re_dam_funny_7dl.ogg"
    $ music_list_7dl["PianoPrinceOfAnime - Always Watching Over You (Violet Evergarden OST)"] = default_7dl_path+"Sound/music/gimme_hand_7dl.ogg"
    $ music_list_7dl["Tracey Chattaway - Love is Here"] = default_7dl_path+"Sound/music/hear_a_love_7dl.ogg"
    $ music_list_7dl["Fabrizio Paterlini - Week #12"] = default_7dl_path+"Sound/music/what_if_7dl.ogg"
#0.37.a
    $ music_list_7dl["Apocalyptica - Faraway"] = default_7dl_path+"Sound/music/faraway_7dl.ogg"
    $ music_list_7dl["Secret Garden - Hymn to Hope"] = default_7dl_path+"Sound/music/last_hope_7dl.ogg"
    $ music_list_7dl["Poets of the Fall - Carnival of Rust"] = default_7dl_path+"Sound/music/ofrust.ogg"
    $ music_list_7dl["Hinkik - Time Leaper"] = default_7dl_path+"Sound/music/pure_energy_7dl.ogg"
    $ music_list_7dl["Acid Jazz vs. Drum'n'Bass - Jungle Radio"] = default_7dl_path+"Sound/music/radio_void_7dl.ogg"
    $ music_list_7dl["Кино - Кончится Лето"] = default_7dl_path+"Sound/music/summer_ends_soon_7dl.ogg"
    $ music_list_7dl["Portishead - Roads (Instrumental Cover)"] = default_7dl_path+"Sound/music/war_to_fight_7dl.ogg"
